### ISSUE TITLE
pls

### ISSUE THREAD

**Issue by EnderMagic** [TheRioMiner/RECC#1]
не могли бы вы открыть код, пожалуйста? 
i like this

**Comment by TheRioMiner** [comment]
It's a private cheat, but I can give the source code if you use this only
for you needs, don't public the source and use it privately.


ср, 15 авг. 2018 г., 8:52 EnderMagic <notifications@github.com>:

**Comment by EnderMagic** [comment]
Yes I will not disclose his source code.

You can send it to my e-mail address: 1123367121@qq.com

**Comment by tickboxs** [comment]
Hi,Could I request the source code as well.I would like to learn from your code,and I will not spread out for sure. mail: cai.charlie@hotmail.com

**Comment by TheRioMiner** [comment]
Now it open-sourced
